swagger: "2.0"
info:
  title: Forester App RESTful API
  description: Documentation for Forester App REST API
  version: 1.0.0
  contact: 
    name: Tomasz Bieniek
    email: tomek-1996-1996@o2.pl
  license:
    name: Copyright (C) Tomasz Bieniek, Inc - All Rights Reserved
host: localhost
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Users
    description: Users operations
paths:
  /user/singup:
    post:
      tags: 
      - Users
      summary: Register a new user
      description: Register a new user in application
      parameters:
        - name: login
          in: body
          description: "User login or e-mail cannot dublicate with existing ones in database. Password must contain at least eight characters, at least one uppercase letter, one lowercase letter and one number. Property \"profile\" is one of the following values: FORESTER, ADMIN, USER"
          required: true
          schema:
           $ref: '#definitions/Login'
      produces:
        - application/json
      responses:
        201:
          description: CREATED
        400:
          description: BAD REQUEST
          schema:
            $ref: '#definitions/Error'
        500: 
          description: INTERNAL SERVER ERROR
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: Header

definitions:
  Error:
    properties:
      message:
        type: string
        example: E-mail already in use
      path:
        type: string
        example: /user/signup
      timestamp:
        type: timestamp
        example: 2019-02-08T20:43:07.316Z
  Login:
      required:
        - login
        - password
        - email
        - profile
      properties:
        login:
          type: string
          example: user123
        password:
          type: string
          example: Password123
        email:
          type: string
          example: example@gmail.com
        profile:
          type: string
          example: USER

