swagger: "2.0"
info:
  title: Forester App RESTful API
  description: Documentation for Forester App REST API
  version: 1.0.0
  contact: 
    name: Tomasz Bieniek
    email: tomek-1996-1996@o2.pl
  license:
    name: Copyright (C) Tomasz Bieniek, Inc - All Rights Reserved
host: localhost
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Users
    description: Users operations
paths:
  /user/singup:
    post:
      tags: 
      - Users
      summary: Register a new user
      description: Register a new user in application
      parameters:
        - name: register
          in: body
          description: "User login or e-mail cannot dublicate with existing ones in database. Password must contain at least eight characters, at least one uppercase letter, one lowercase letter and one number. Property \"profile\" is one of the following values: FORESTER, ADMIN, USER"
          required: true
          schema:
           $ref: '#definitions/Register'
      produces:
        - application/json
      responses:
        201:
          description: CREATED
        400:
          description: BAD REQUEST
          schema:
            $ref: '#definitions/Error'
        500: 
          description: INTERNAL SERVER ERROR
  /user/login:
    post:
      tags: 
      - Users
      summary: Login with user credentials
      description: Login for existing users
      parameters:
        - name: login
          in: body
          description: "User login data"
          required: true
          schema:
           $ref: '#definitions/Login'
      produces:
        - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#definitions/LoginResponse'
        400:
          description: BAD REQUEST
          schema:
            $ref: '#definitions/Error'
        401:
          description: UNAUTHORIZED
          schema:
            $ref: '#definitions/Error'
        500: 
          description: INTERNAL SERVER ERROR

securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: Header

definitions:
  Error:
    properties:
      message:
        type: string
      path:
        type: string
      timestamp:
        type: string
  Register:
      required:
        - login
        - password
        - email
        - profile
      properties:
        login:
          type: string
          example: user123
        password:
          type: string
          example: Password123
        email:
          type: string
          example: example@gmail.com
        profile:
          type: string
          example: USER
  Login:
    required:
    - login
    - password
    properties:
      login: 
        type: string
        example: user123
      password:
        type: string
        example: Password123
  LoginResponse:
    properties:
      message:
        type: string
        example: Authorization successful
      token:
        type: string
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2dpbiI6InRvbWFzejEyMyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTU0OTcyNjkxMiwiZXhwIjoxNTQ5NzI4NzEyfQ.zRnIv_-SIyL3uJYjs3dnki11xbptFZF0qxrW2B_Mt2U
      expiresIn:
        type: integer
        example: 1800
    


